SpectrumHelper/Models/ErrorViewModel.cs
using System;

namespace SpectrumHelper.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

SpectrumHelper/ViewModels/IncomingParameters.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SpectrumHelper.ViewModels
{
	public class IncomingParameters
	{
		[Display (Name = "Нижняя частота")]
		[Required (ErrorMessage = "Поле не может быть пустым")]
		public decimal LowerFrequency { get; set; }

		[Display (Name = "Верхняя частота")]
		[Required(ErrorMessage = "Поле не может быть пустым")]
		public decimal UpperFrequency { get; set; }

		[Display(Name = "Шаг")]
		public decimal step { get; set; }
	}
}

SpectrumHelper/Controllers/AnalyzeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SpectrumHelper.ViewModels;

namespace SpectrumHelper.Controllers
{
	public class AnalyzeController : Controller
	{
		public IActionResult Index()
		{

			return View();
		}

		[HttpPost]
		public IActionResult Index(IncomingParameters incomingParameters)
		{
		 return View( );
		}
	}
}

SpectrumHelper/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SpectrumHelper.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SpectrumHelper.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

SpectrumHelper/Views/Analyze/Index.cshtml
@model SpectrumHelper.ViewModels.IncomingParameters


@{
	ViewData["Title"] = "Ввод параметров";
}
<h1>@ViewData["Title"]</h1>

<p>Введите параметры для дальнейшей работы</p>

<form asp-action="Index" method="post" class="form-group">
	<div class="row">

		<div class="col-md-6">
			<button type="button" class=" btn btn-warning" style="margin: 15px; margin-left: 5px">Подключиться к анализатору спектра</button>
		</div>
		<br />
		<div class="col-md-6">
			<span style=" color: green; font-size: 20px">
				<br />
				Соединение установлено
			</span>
		</div>

		<div style="margin-top: 30px; margin-bottom: 30px" class="col-md-4">
			<label asp-for="LowerFrequency"></label>
			<input asp-for="LowerFrequency" class="form-control">
			<span asp-validation-for="LowerFrequency" class="alert-danger"></span>
		</div>
		<div style="margin-top: 30px; margin-bottom: 30px" class="col-md-4">
			<label asp-for="UpperFrequency"></label>
			<input asp-for="UpperFrequency" class="form-control" />
			<span asp-validation-for="UpperFrequency" class="alert-danger"></span>
		</div>
		<div style="margin-top: 30px; margin-bottom: 30px" class="col-md-4">
			<label asp-for="step"></label>
			<input asp-for="step" class="form-control" />
			<span asp-validation-for="step" class="alert-danger"></span>
		</div>
		<div>
			<button style="margin: 25px" type="submit" class=" btn btn-primary" style="margin-top: 35px">Подтвердить ввод</button>
		</div>
		
	</div>

</form>
<div style="font-size: 21px">
	<span>Инструкция:</span>
	<ol>
		<li>В поля "Верхняя частота" и "Нижняя частота" введите частоты, задающие диапазон измерения</li>
		<li>Поле "Шаг" предназначено для ввода интервала и не является обязательным. </li>
		<li>Нажмите кнопку "Ввести параметры" и дождитесь переадрессации на страницу с результатами </li>
	</ol>
</div>

SpectrumHelper/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
	<h1 class="display-4">Вас приветствует Spectrum Helper</h1>
	<p class="description" style="font-size: 18px">
		Данный программный продукт является отличным дополнением к анализатору спектра. Основной задачей данного приложения является <br>
		классификация сигналов в спектре сигнала реального времени. В основе приложения лежит свёрточная нейронная сеть, <br> работающая на алгортмах глубокого обучения
	</p>
	<div class="home-image"><img src="~/statics/maxresdefault.jpg" /></div>
	<div>
	<form method="post" asp-page="/Home/Index">
		<input  class="btn btn-primary" style="margin-top: 600px; font-size: 22px" type="submit" value="Начать работу" asp-page-handler="Redirect1" />
	</form>
		</div>
</div>

SpectrumHelper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SpectrumHelper</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SpectrumHelper</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						@*<li class="nav-item">
			<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
		</li>*@
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Analyze" asp-action="Index">Analyzer</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Results" asp-action="Index">Results</a>
						</li>
					</ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SpectrumHelper
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>